name: pelayanan_laundri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  image_picker: ^0.8.6
  get_storage: ^2.1.1
  flutter_slidable: ^3.1.0
  intl: ^0.19.0
  page_transition: ^2.0.4
  flutter_screenutil: ^5.1.1
  fluttertoast: ^8.0.7
  url_launcher: ^6.3.0
  firebase_storage: ^11.0.16
  flutter_launcher_icons: "^0.13.1"

  


  flutter: 
    sdk: flutter


  image: ^4.2.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  screenshot: ^3.0.0
  image_gallery_saver:
    git:
        url: https://github.com/knottx/image_gallery_saver.git
        ref: knottx-latest
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  open_file: ^3.3.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/iconaplikasi.png"
  

flutter: 
  assets:
    - assets/images/
   
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf   
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        

  uses-material-design: true

