// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHueLFIqF7h6GFDTuRyVxjNGikUVfios',
    appId: '1:665224682928:web:76d5f6a6e10656cc3d4a75',
    messagingSenderId: '665224682928',
    projectId: 'my-firebase-project-76e33',
    authDomain: 'my-firebase-project-76e33.firebaseapp.com',
    storageBucket: 'my-firebase-project-76e33.firebasestorage.app',
    measurementId: 'G-MS08ZGZ3G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADa-k0P_fB6wMf0BvYl-rud-R9jAAGifo',
    appId: '1:665224682928:android:b14dfa08b850236e3d4a75',
    messagingSenderId: '665224682928',
    projectId: 'my-firebase-project-76e33',
    storageBucket: 'my-firebase-project-76e33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHgn1UcraK-OrGf_qif97igMTMBFu-vvs',
    appId: '1:665224682928:ios:9be3cb2ac1dacbec3d4a75',
    messagingSenderId: '665224682928',
    projectId: 'my-firebase-project-76e33',
    storageBucket: 'my-firebase-project-76e33.firebasestorage.app',
    iosBundleId: 'com.honeycumb.laundryku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHgn1UcraK-OrGf_qif97igMTMBFu-vvs',
    appId: '1:665224682928:ios:9be3cb2ac1dacbec3d4a75',
    messagingSenderId: '665224682928',
    projectId: 'my-firebase-project-76e33',
    storageBucket: 'my-firebase-project-76e33.firebasestorage.app',
    iosBundleId: 'com.honeycumb.laundryku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHueLFIqF7h6GFDTuRyVxjNGikUVfios',
    appId: '1:665224682928:web:85434e75d30f9b663d4a75',
    messagingSenderId: '665224682928',
    projectId: 'my-firebase-project-76e33',
    authDomain: 'my-firebase-project-76e33.firebaseapp.com',
    storageBucket: 'my-firebase-project-76e33.firebasestorage.app',
    measurementId: 'G-T1GHSBLXQQ',
  );
}
